services:
  tumbleweed:
    image: pkg-assistant-tumbleweed
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: tumbleweed
        INSTALL_DEPS: zypper in -y pkexec
  fedora:
    image: pkg-assistant-fedora
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: fedora
        INSTALL_DEPS: dnf install -y pkexec
  ubuntu:
    image: pkg-assistant-ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: ubuntu
        REFRESH_REPO: apt-get update
        INSTALL_DEPS: apt-get install -y pkexec
  archlinux:
    image: pkg-assistant-archlinux
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: archlinux
        INSTALL_DEPS: pacman -Sy --noconfirm polkit