services:
  tumbleweed:
    image: pkg-assistant-tumbleweed
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: tumbleweed
  fedora:
    image: pkg-assistant-fedora
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: fedora
  ubuntu:
    image: pkg-assistant-ubuntu
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: ubuntu
  archlinux:
    image: pkg-assistant-archlinux
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DISTRO_NAME: archlinux