[service]
enable_service = true
update_check_frequency = 30
download_in_background = true
update_on_reboot = false

[package]
package_type = "deb"
check_update_command = "apt list --upgradable"
download_command = "apt-get update && apt-get upgrade -y --download-only"
update_command = "apt-get upgrade"
cached_package_path = "/var/cache/apt/archives"