[service]
enable_service = true
update_check_frequency = 30
download_in_background = true
update_on_reboot = false

[package]
package_manager = "dnf"
download_command = "dnf upgrade --downloadonly -y"
update_command = "dnf upgrade -y"
cached_package_path = "/var/cache/libdnf5"