[service]
enable_service = true
update_check_frequency = 30
download_in_background = true
update_on_reboot = false

[package]
package_manager = "pacman"
download_command = "pacman -Syuw --noconfirm"
update_command = "pacman -Syu --noconfirm"
cached_package_path = "/var/cache/pacman/pkg"