[service]
enable_service = true
update_check_frequency = 30
download_in_background = true
update_on_reboot = false

[package]
package_type = "rpm"
check_update_command = "zypper lu"
download_command = "zypper dup -dy"
update_command = "zypper dup"
cached_package_path = "/var/cache/zypp/packages"